use crate::application::InitOperation;
use ayni_core::{AdapterRegistry, Language, ProjectLayout, SignalKind};
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;
use std::process::ExitCode;

pub(crate) fn run(operation: InitOperation, registry: &AdapterRegistry) -> ExitCode {
    match init(&operation.repo_root, operation.write, registry) {
        Ok(output) => {
            println!("{output}");
            ExitCode::SUCCESS
        }
        Err(error) => {
            eprintln!("{error}");
            ExitCode::from(2)
        }
    }
}

fn init(repo_root: &Path, write: bool, registry: &AdapterRegistry) -> Result<String, String> {
    let root = repo_root.canonicalize().map_err(|error| {
        format!(
            "failed to establish repository root {}: {error}",
            repo_root.display()
        )
    })?;
    if !root.is_dir() {
        return Err(format!(
            "repository root is not a directory: {}",
            root.display()
        ));
    }

    let mut discovered = registry
        .adapters()
        .iter()
        .filter_map(|adapter| {
            let discovery = adapter.discover_project_roots(&root);
            let candidate_roots = if discovery.layout == ProjectLayout::ControlledMonorepo
                && discovery.roots.iter().any(|root| root.path == ".")
            {
                vec![String::from(".")]
            } else {
                discovery.analyzable_roots()
            };
            let roots = minimal_roots(
                candidate_roots
                    .into_iter()
                    .filter(|path| is_reviewable_source_root(path))
                    .collect(),
            );
            let test_tools = adapter
                .catalog()
                .iter()
                .filter(|entry| entry.for_signals.contains(&SignalKind::Test))
                .map(|entry| entry.name)
                .collect::<Vec<_>>();
            (!roots.is_empty()).then_some((adapter.language(), roots, test_tools))
        })
        .collect::<Vec<_>>();
    discovered.sort_by_key(|(language, _, _)| *language);
    if discovered.is_empty() {
        return Err(String::from(
            "no supported project roots were discovered; create .ayni.toml explicitly",
        ));
    }

    let policy = render_policy(&discovered);
    if !write {
        return Ok(policy);
    }

    let destination = root.join(".ayni.toml");
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&destination)
        .map_err(|error| {
            if destination.exists() {
                format!(
                    "refusing to overwrite {}; run `ayni init --dry-run` to review a proposal",
                    destination.display()
                )
            } else {
                format!("failed to create {}: {error}", destination.display())
            }
        })?;
    file.write_all(policy.as_bytes())
        .and_then(|()| file.sync_all())
        .map_err(|error| format!("failed to write {}: {error}", destination.display()))?;
    Ok(format!(
        "wrote {}\n\n{}",
        destination.display(),
        policy.trim_end()
    ))
}

fn is_reviewable_source_root(root: &str) -> bool {
    root == "."
        || !root.split('/').any(|component| {
            matches!(
                component,
                ".ayni"
                    | ".git"
                    | "target"
                    | "node_modules"
                    | ".venv"
                    | "venv"
                    | ".gradle"
                    | ".vitepress"
                    | "build"
                    | "dist"
                    | "coverage"
                    | "__pycache__"
            )
        })
}

fn minimal_roots(mut roots: Vec<String>) -> Vec<String> {
    roots.sort_by_key(|root| (root.split('/').count(), root.clone()));
    let mut selected = Vec::<String>::new();
    for root in roots {
        let nested = selected.iter().any(|ancestor| {
            ancestor == "."
                || root == *ancestor
                || root
                    .strip_prefix(ancestor)
                    .is_some_and(|remainder| remainder.starts_with('/'))
        });
        if !nested {
            selected.push(root);
        }
    }
    selected.sort();
    selected
}

fn render_policy(discovered: &[(Language, Vec<String>, Vec<&'static str>)]) -> String {
    let languages = discovered
        .iter()
        .map(|(language, _, _)| toml_string(language.as_str()))
        .collect::<Vec<_>>()
        .join(", ");
    let mut output = format!(
        "# Generated by `ayni init`; review this policy before committing it.\n\
[checks]\n\
test = true\n\
coverage = false\n\
size = false\n\
complexity = false\n\
deps = false\n\
mutation = false\n\n\
[languages]\n\
enabled = [{languages}]\n"
    );
    for (language, roots, test_tools) in discovered {
        let roots = roots
            .iter()
            .map(|root| toml_string(root))
            .collect::<Vec<_>>()
            .join(", ");
        let tool_note = if test_tools.is_empty() {
            String::from("built-in adapter measurement")
        } else {
            test_tools.join(", ")
        };
        output.push_str(&format!(
            "\n# Initial test tools: {tool_note}\n[{}]\nroots = [{}]\n",
            language.as_str(),
            roots
        ));
    }
    output
}

fn toml_string(value: &str) -> String {
    toml::Value::String(value.to_owned()).to_string()
}

#[cfg(test)]
mod tests {
    use super::{init, is_reviewable_source_root, minimal_roots};
    use crate::registry::build_registry;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn generated_and_dependency_roots_are_never_proposed() {
        assert!(is_reviewable_source_root("."));
        assert!(is_reviewable_source_root("examples/rust/mono"));
        assert!(!is_reviewable_source_root(
            ".ayni/environment/cache/project"
        ));
        assert!(!is_reviewable_source_root("apps/web/node_modules/pkg"));
        assert!(!is_reviewable_source_root("target/fixture"));
        assert!(!is_reviewable_source_root("docs/.vitepress/cache/deps"));
        assert_eq!(
            minimal_roots(vec![
                String::from("workspace/member"),
                String::from("workspace"),
                String::from("standalone"),
            ]),
            vec![String::from("standalone"), String::from("workspace")]
        );
    }

    #[test]
    fn dry_run_discovers_projects_without_writing() {
        let directory = TempDir::new().expect("tempdir");
        fs::write(
            directory.path().join("Cargo.toml"),
            "[package]\nname='fixture'\nversion='0.1.0'\n",
        )
        .expect("manifest");

        let output = init(directory.path(), false, &build_registry()).expect("preview");
        assert!(output.contains("enabled = [\"rust\"]"));
        assert!(output.contains("[rust]\nroots = [\".\"]"));
        assert!(!directory.path().join(".ayni.toml").exists());
    }

    #[test]
    fn write_is_explicit_and_never_overwrites() {
        let directory = TempDir::new().expect("tempdir");
        fs::write(
            directory.path().join("go.mod"),
            "module example.com/fixture\n",
        )
        .expect("manifest");

        init(directory.path(), true, &build_registry()).expect("write");
        let path = directory.path().join(".ayni.toml");
        let policy = fs::read_to_string(&path).expect("policy");
        assert!(policy.contains("enabled = [\"go\"]"));
        let error = init(directory.path(), true, &build_registry()).expect_err("no overwrite");
        assert!(error.contains("refusing to overwrite"));
        assert_eq!(fs::read_to_string(path).expect("policy"), policy);
    }
}
